import { Offset, Tiles } from "types";

export const board = [
  [
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
  ],
  [
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
  ],
  [
    "road",
    "grass",
    "river",
    "river",
    "road",
    "tower",
    "river",
    "river",
    "road",
    "grass",
    "river",
    "river",
  ],
  [
    "road",
    "river",
    "river",
    "grass",
    "road",
    "river",
    "river",
    "grass",
    "road",
    "river",
    "river",
    "grass",
    "road",
  ],
  [
    "road",
    "swamp",
    "grass",
    "road",
    "road",
    "grass",
    "grass",
    "road",
    "road",
    "grass",
    "grass",
    "road",
  ],
  [
    "grass",
    "road",
    "swamp",
    "road",
    "grass",
    "road",
    "ditch",
    "road",
    "grass",
    "road",
    "grass",
    "road",
    "grass",
  ],
  [
    "grass",
    "road",
    "road",
    "grass",
    "grass",
    "road",
    "road",
    "grass",
    "grass",
    "road",
    "road",
    "grass",
  ],
  [
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
  ],
  [
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
  ],
  [
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
  ],
  [
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
  ],
  [
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
    "grass",
    "road",
    "grass",
    "grass",
  ],
] as Array<Array<Tiles>>;

const towerRow = board.find((row) => row.includes("tower")) as Tiles[];
const towerY = board.indexOf(towerRow);
const towerX = towerRow.indexOf("tower");

export const towerOffset: Offset = [towerX, towerY];

const ditchRow = board.find((row) => row.includes("ditch")) as Tiles[];
const ditchY = board.indexOf(ditchRow);
const ditchX = ditchRow.indexOf("ditch");

export const ditchOffset: Offset = [ditchX, ditchY];

export const tilesDictionary = {
  river:
    "url('/tiles/waveWater.png') center no-repeat, url('/tiles/tileWater.png') center",
  grass: "url('/tiles/tileGrass.png') no-repeat",
  road: "url('/tiles/tileDirt.png') no-repeat",
  swamp:
    "url('/tiles/rockStone_moss3.png'), url('/tiles/tileGrass.png') no-repeat",
  tower: "url('/tiles/rockRing.png'), url('/tiles/tileGrass.png') no-repeat",
  ditch: "url('/tiles/tileMagic.png') no-repeat",
};
