import { Card } from "types";

const cards: Card[] = [
  {
    ids: [
      "melgar",
      "bogenhaffen",
      "grunberg-archers",
      "reikwald",
      "altdorf",
      "grunburg-arms",
      "blitzens",
      "normands",
      "delbornes",
      "empire-knights",
    ],
    img: "/cards/playing-card-13.png",
    moves: 1,
  },
  {
    ids: [
      "bogenhaffen",
      "grunberg-archers",
      "reikwald",
      "altdorf",
      "grunburg-arms",
    ],
    img: "/cards/playing-card-14.png",
    moves: 1,
  },
  {
    ids: ["canon"],
    img: "/cards/playing-card-15.png",
    moves: 1,
  },
  {
    ids: ["canon"],
    img: "/cards/playing-card-15.png",
    moves: 1,
  },
  {
    ids: ["canon"],
    img: "/cards/playing-card-15.png",
    moves: 1,
  },
  {
    ids: ["canon"],
    img: "/cards/playing-card-15.png",
    moves: 1,
  },
  {
    ids: ["bogenhaffen", "grunberg-archers"],
    img: "/cards/playing-card-16.png",
    moves: 1,
  },
  {
    ids: ["bogenhaffen", "grunberg-archers"],
    img: "/cards/playing-card-16.png",
    moves: 1,
  },
  {
    ids: ["blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-17.png",
    moves: 1,
  },
  {
    ids: ["blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-17.png",
    moves: 1,
  },
  {
    ids: ["blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-17.png",
    moves: 1,
  },
  {
    ids: ["blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-17.png",
    moves: 1,
  },
  {
    ids: [
      "melgar",
      "bogenhaffen",
      "grunberg-archers",
      "reikwald",
      "altdorf",
      "grunburg-arms",
    ],
    img: "/cards/playing-card-18.png",
    moves: 1,
  },
  {
    ids: [
      "melgar",
      "bogenhaffen",
      "grunberg-archers",
      "reikwald",
      "altdorf",
      "grunburg-arms",
    ],
    img: "/cards/playing-card-18.png",
    moves: 1,
  },
  {
    ids: [
      "melgar",
      "bogenhaffen",
      "grunberg-archers",
      "reikwald",
      "altdorf",
      "grunburg-arms",
    ],
    img: "/cards/playing-card-18.png",
    moves: 1,
  },
  {
    ids: [
      "melgar",
      "bogenhaffen",
      "grunberg-archers",
      "reikwald",
      "altdorf",
      "grunburg-arms",
    ],
    img: "/cards/playing-card-18.png",
    moves: 1,
  },
  {
    ids: ["empire-knights"],
    img: "/cards/playing-card-19.png",
    moves: 1,
  },
  {
    ids: ["empire-knights"],
    img: "/cards/playing-card-19.png",
    moves: 1,
  },
  {
    ids: ["empire-knights", "blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-20.png",
    moves: 1,
  },
  {
    ids: ["empire-knights", "blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-20.png",
    moves: 1,
  },
  {
    ids: ["empire-knights", "blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-20.png",
    moves: 1,
  },
  {
    ids: ["empire-knights", "blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-20.png",
    moves: 1,
  },
  {
    ids: ["empire-knights", "blitzens", "normands", "delbornes"],
    img: "/cards/playing-card-22.png",
    moves: 1,
  },
  {
    ids: ["empire-knights"],
    img: "/cards/playing-card-21.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "doomguard", "fellmoors"],
    img: "/cards/playing-card-1.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "doomguard", "fellmoors", "gorebands", "finmars"],
    img: "/cards/playing-card-2.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "doomguard", "fellmoors", "gorebands", "finmars"],
    img: "/cards/playing-card-2.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "doomguard", "fellmoors", "gorebands", "finmars"],
    img: "/cards/playing-card-2.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "doomguard", "fellmoors", "gorebands", "finmars"],
    img: "/cards/playing-card-2.png",
    moves: 1,
  },
  {
    ids: ["gorefists"],
    img: "/cards/playing-card-3.png",
    moves: 1,
  },
  {
    ids: ["gorefists"],
    img: "/cards/playing-card-3.png",
    moves: 1,
  },
  {
    ids: ["grom", "uglub", "gazkulls", "zogrods"],
    img: "/cards/playing-card-4.png",
    moves: 1,
  },
  {
    ids: ["grom", "uglub", "gazkulls", "zogrods"],
    img: "/cards/playing-card-4.png",
    moves: 1,
  },
  {
    ids: ["grom", "uglub", "gazkulls", "zogrods"],
    img: "/cards/playing-card-4.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "blackfangs", "bogrots"],
    img: "/cards/playing-card-5.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "blackfangs", "bogrots"],
    img: "/cards/playing-card-5.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "blackfangs", "bogrots"],
    img: "/cards/playing-card-5.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "blackfangs", "bogrots"],
    img: "/cards/playing-card-5.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "blackfangs", "bogrots"],
    img: "/cards/playing-card-5.png",
    moves: 1,
  },
  {
    ids: ["grimorg"],
    img: "/cards/playing-card-7.png",
    moves: 0,
  },
  {
    ids: ["grimorg"],
    img: "/cards/playing-card-7.png",
    moves: 0,
  },
  {
    ids: ["grimorg"],
    img: "/cards/playing-card-7.png",
    moves: 0,
  },
  {
    ids: ["grimorg"],
    img: "/cards/playing-card-7.png",
    moves: 0,
  },
  {
    ids: ["grimorg"],
    img: "/cards/playing-card-7.png",
    moves: 0,
  },
  {
    ids: ["grom", "uglub", "gazkulls", "zogrods", "bale", "flint"],
    img: "/cards/playing-card-10.png",
    moves: 1,
  },
  {
    ids: ["grom", "uglub", "gazkulls", "zogrods", "bale", "flint"],
    img: "/cards/playing-card-10.png",
    moves: 1,
  },
  {
    ids: [
      "grom",
      "uglub",
      "gazkulls",
      "zogrods",
      "bale",
      "flint",
      "doomguard",
      "fellmoors",
      "gorebands",
      "finmars",
    ],
    img: "/cards/playing-card-11.png",
    moves: 1,
  },
  {
    ids: ["gorefists", "grom", "uglub", "bale", "flint"],
    img: "/cards/playing-card-12.png",
    moves: 1,
  },
  {
    ids: [
      "grom",
      "uglub",
      "gazkulls",
      "zogrods",
      "bale",
      "flint",
      "doomguard",
      "fellmoors",
      "gorebands",
      "finmars",
      "blackfangs",
      "bogrots",
      "gorefists",
    ],
    img: "/cards/playing-card-23.png",
    moves: 1,
  },
  {
    ids: ["blackfangs", "bogrots"],
    img: "/cards/playing-card-6.png",
    moves: 2,
  },
  {
    ids: ["blackfangs", "bogrots"],
    img: "/cards/playing-card-6.png",
    moves: 2,
  },
  {
    ids: ["blackfangs", "bogrots"],
    img: "/cards/playing-card-6.png",
    moves: 2,
  },
  {
    ids: ["blackfangs", "bogrots"],
    img: "/cards/playing-card-6.png",
    moves: 2,
  },
  {
    ids: ["blackfangs", "bogrots"],
    img: "/cards/playing-card-6.png",
    moves: 2,
  },
  {
    ids: ["blackfangs", "bogrots", "grom", "uglub"],
    img: "/cards/playing-card-9.png",
    moves: 1,
  },
  {
    ids: ["blackfangs", "bogrots", "grom", "uglub"],
    img: "/cards/playing-card-9.png",
    moves: 1,
  },
  {
    ids: ["blackfangs", "bogrots", "grom", "uglub", "bale", "flint"],
    img: "/cards/playing-card-8.png",
    moves: 1,
  },
];

export default cards;
