import { Unit, UnitId } from "types";

export const canEnterTower: UnitId[] = [
  "grunberg-archers",
  "bogenhaffen",
  "melgar",
  "reikwald",
  "grunburg-arms",
  "altdorf",
  "gorebands",
  "finmars",
  "bale",
  "flint",
  "gazkulls",
  "zogrods",
  "grom",
  "uglub",
  "doomguard",
  "fellmoors",
];

export const archersAndCrossbow: UnitId[] = [
  "grunberg-archers",
  "bogenhaffen",
  "melgar",
  "doomguard",
  "fellmoors",
];

const units: Unit[] = [
  {
    name: "The Mighty Canon",
    id: "canon",
    x: null,
    y: null,
    src: "/units/imperial-4.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 8,
    combatValue: 2,
    damageSustained: 0,
  },
  {
    name: "Lord Knights of the Empire",
    id: "empire-knights",
    x: null,
    y: null,
    src: "/units/imperial-6.png",
    alt: "/imperial-6",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 1,
    combatValue: 5,
    damageSustained: 0,
  },
  {
    name: "Imperial Archers of Grunburg",
    id: "grunberg-archers",
    x: null,
    y: null,
    src: "/units/imperial-3.png",
    alt: "/imperial-3",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 2,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Imperial Archers of Bogenhaffen",
    id: "bogenhaffen",
    x: null,
    y: null,
    src: "/units/imperial-3.png",
    alt: "/imperial-3",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 2,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Crossbowmen Melgar's",
    id: "melgar",
    x: null,
    y: null,
    src: "/units/imperial-2.png",
    alt: "/imperial-3",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 3,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Men-At-Arms of Reikwald",
    id: "reikwald",
    x: null,
    y: null,
    src: "/units/imperial-1.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 1,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Men-At-Arms of Grunburg",
    id: "grunburg-arms",
    x: null,
    y: null,
    src: "/units/imperial-1.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 1,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Men-At-Arms of Altdorf",
    id: "altdorf",
    x: null,
    y: null,
    src: "/units/imperial-1.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 1,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Imperial Knights of Baron Delborne's",
    id: "delbornes",
    x: null,
    y: null,
    src: "/units/imperial-5.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 1,
    combatValue: 4,
    damageSustained: 0,
  },
  {
    name: "Imperial Knights of Duke Blitzen's",
    id: "blitzens",
    x: null,
    y: null,
    src: "/units/imperial-5.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 1,
    combatValue: 4,
    damageSustained: 0,
  },
  {
    name: "Imperial Knights Prince Normand's",
    id: "normands",
    x: null,
    y: null,
    src: "/units/imperial-5.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Imperial",
    range: 1,
    combatValue: 4,
    damageSustained: 0,
  },
  {
    name: "Champions of Chaos Gorefist's",
    id: "gorefists",
    x: null,
    y: null,
    src: "/units/chaos-7.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 5,
    damageSustained: 0,
  },
  {
    name: "Ogre Champion of Grimorg",
    id: "grimorg",
    x: null,
    y: null,
    src: "/units/chaos-6.png",
    alt: "/imperial-6",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 4,
    damageSustained: 0,
  },
  {
    name: "Chaos Warriors Goreband's",
    id: "gorebands",
    x: null,
    y: null,
    src: "/units/chaos-4.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 4,
    damageSustained: 0,
  },
  {
    name: "Chaos Warriors Finmar's",
    id: "finmars",
    x: null,
    y: null,
    src: "/units/chaos-4.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 4,
    damageSustained: 0,
  },
  {
    name: "Wolf Riders Bogrot's",
    id: "bogrots",
    x: null,
    y: null,
    src: "/units/chaos-5.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 2,
    damageSustained: 0,
  },
  {
    name: "Wolf Riders Black Fang's",
    id: "blackfangs",
    x: null,
    y: null,
    src: "/units/chaos-5.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 2,
    damageSustained: 0,
  },
  {
    name: "Beastmen of Bale",
    id: "bale",
    x: null,
    y: null,
    src: "/units/chaos-8.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Beastmen of Flint",
    id: "flint",
    x: null,
    y: null,
    src: "/units/chaos-8.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Orcs Gazkull's",
    id: "gazkulls",
    x: null,
    y: null,
    src: "/units/chaos-2.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Orcs Zogrod's",
    id: "zogrods",
    x: null,
    y: null,
    src: "/units/chaos-2.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 3,
    damageSustained: 0,
  },
  {
    name: "Goblins of Grom",
    id: "grom",
    x: null,
    y: null,
    src: "/units/chaos-1.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 2,
    damageSustained: 0,
  },
  {
    name: "Goblins of Uglub",
    id: "uglub",
    x: null,
    y: null,
    src: "/units/chaos-1.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 1,
    combatValue: 2,
    damageSustained: 0,
  },
  {
    name: "Chaos Archers Doomguard",
    id: "doomguard",
    x: null,
    y: null,
    src: "/units/chaos-3.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 2,
    combatValue: 2,
    damageSustained: 0,
  },
  {
    name: "Chaos Archers Fellmor's",
    id: "fellmoors",
    x: null,
    y: null,
    src: "/units/chaos-3.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
    hasAttacked: false,
    army: "Chaos",
    range: 2,
    combatValue: 2,
    damageSustained: 0,
  },
];

export default units;
