import { Unit } from "types";

const units: Unit[] = [
  {
    name: "The Mighty Canon",
    id: "canon",
    x: 6,
    y: 5,
    src: "/units/imperial-4.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false
  },
  {
    name: "Lord Knights of the Empire",
    id: "empire-knights",
    x: 5,
    y: 4,
    src: "/units/imperial-6.png",
    alt: "/imperial-6",
    isActive: false,
    hasMoved: false
  },
  {
    name: "Imperial Archers of Grunburg",
    id: "grunberg-archers",
    x: 3,
    y: 3,
    src: "/units/imperial-3.png",
    alt: "/imperial-3",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Imperial Archers of Bogenhaffen",
    id: "bogenhaffen",
    x: 7,
    y: 3,
    src: "/units/imperial-3.png",
    alt: "/imperial-3",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Crossbowmen Melgar's",
    id: "melgar",
    x: 6,
    y: 1,
    src: "/units/imperial-2.png",
    alt: "/imperial-3",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Men-At-Arms of Reikwald",
    id: "reikwald",
    x: 4,
    y: 3,
    src: "/units/imperial-1.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Men-At-Arms of Grunburg",
    id: "grunburg-arms",
    x: 1,
    y: 1,
    src: "/units/imperial-1.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Men-At-Arms of Altdorf",
    id: "altdorf",
    x: 8,
    y: 3,
    src: "/units/imperial-1.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Imperial Knights of Baron Delborne's",
    id: "delbornes",
    x: 10,
    y: 5,
    src: "/units/imperial-5.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Imperial Knights of Duke Blitzen's",
    id: "blitzens",
    x: 9,
    y: 5,
    src: "/units/imperial-5.png",
    alt: "/imperial-1",
    isActive: false, hasMoved: false,
  },
  {
    name: "Imperial Knights Prince Normand's",
    id: "normands",
    x: 8,
    y: 5,
    src: "/units/imperial-5.png",
    alt: "/imperial-1",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Champions of Chaos Gorefist's",
    id: "gorefists",
    x: 1,
    y: 10,
    src: "/units/chaos-7.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Ogre Champion of Grimorg",
    id: "grimorg",
    x: 1,
    y: 9,
    src: "/units/chaos-6.png",
    alt: "/imperial-6",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Chaos Warriors Goreband's",
    id: "gorebands",
    x: 3,
    y: 10,
    src: "/units/chaos-4.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Chaos Warriors Finmar's",
    id: "finmars",
    x: 4,
    y: 10,
    src: "/units/chaos-4.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Wolf Riders Bogrot's",
    id: "bogrots",
    x: 3,
    y: 9,
    src: "/units/chaos-5.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Wolf Riders Black Fang's",
    id: "blackfangs",
    x: 4,
    y: 9,
    src: "/units/chaos-5.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Beastmen of Bale",
    id: "bale",
    x: 5,
    y: 9,
    src: "/units/chaos-8.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Beastmen of Flint",
    id: "flint",
    x: 5,
    y: 10,
    src: "/units/chaos-8.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Orcs Gazkull's",
    id: "gazkulls",
    x: 6,
    y: 10,
    src: "/units/chaos-2.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Orcs Zogrod's",
    id: "zogrods",
    x: 7,
    y: 11,
    src: "/units/chaos-2.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Goblins of Grom",
    id: "grom",
    x: 7,
    y: 9,
    src: "/units/chaos-1.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Goblins of Uglub",
    id: "uglub",
    x: 7,
    y: 10,
    src: "/units/chaos-1.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Chaos Archers Doomguard",
    id: "doomguard",
    x: 3,
    y: 11,
    src: "/units/chaos-3.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  },
  {
    name: "Chaos Archers Fellmor's",
    id: "fellmoors",
    x: 4,
    y: 11,
    src: "/units/chaos-3.png",
    alt: "/imperial-4",
    isActive: false,
    hasMoved: false,
  }
];

export default units;
